<Project Sdk="Dalamud.NET.Sdk/15.0.0">

    <PropertyGroup>
        <AssemblyName>ChatTools</AssemblyName>
        <Version>4.0.3</Version>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Authors>serifine</Authors>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <PreserveCompilationContext>false</PreserveCompilationContext>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <PackageProjectUrl>https://github.com/serifine/XIV-Chat-Tools</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="images\icon.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
      <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="DalamudPackager" Version="15.0.0" />
      <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
    </ItemGroup>
</Project>
